### ISSUE TITLE
Dallas Temp Probe Calibration from Frontend

### ISSUE THREAD

**Issue by TheRealFalseReality** [TheRealFalseReality/aquapi#2]
Want to add the ability to calibrate the Dallas temp probes as needed.

**Comment by TheRealFalseReality** [comment]
The only thing I can get to a variable for the True value is a substutution, which I do not know how to change via the frontend. I can't insert any lambdas to insert the state from another number sensor, it expects a float. I am putting this on pause.

This works for now:
```
substitutions:
  # calibration variables
  # calibration at 0C - Ice Water
  cal_0: "0.0"
  # calibration at 100C - Boiling Water
  cal_100: "100.0"

sensor:
 # Temperature Probes 1
  - platform: dallas
    id: temp_1
    icon: mdi:thermometer-lines
    index: 0
    name: "Temperature"
    filters:
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 0.0 -> ${cal_0}
            - 100.0 -> ${cal_100}
```

Won't work:
```
number:
  # Calibration Temp. at 0C - Ice Bath
  - platform: template
    name: "Calibration Temp. at 0C - Ice Bath"
    id: cal_0
    icon: mdi:snowflake-alert
    optimistic: true
    min_value: -10.0
    max_value: 10.0
    step: .1
    restore_value: True
    initial_value: 0.0
    entity_category: "Config"

 # Temperature Probes 1
  - platform: dallas
    id: temp_1
    icon: mdi:thermometer-lines
    index: 0
    name: "Temperature"
    filters:
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 0.0 -> id(cal_0).state
            - 100.0 -> !lambda 'id(cal_100).state';
```
