### ISSUE TITLE
Aquapi bootilooping with factory image

### ISSUE THREAD

**Issue by kiguy2052** [TheRealFalseReality/aquapi#68]
**Describe the bug**
After flashing a fresh image using the default yaml, the device reboots immediately upon finishing setup.

**To Reproduce**
Not sure if reproducible

**Expected behavior**
No bootloop obvs

**Screenshots**
[logs (1).txt](https://github.com/user-attachments/files/16120366/logs.1.txt)
![image](https://github.com/TheRealFalseReality/aquapi/assets/10635940/f70b9bfe-27bb-4fbc-8feb-8b9a0c4d8e6a)
![image](https://github.com/TheRealFalseReality/aquapi/assets/10635940/5f824778-36ef-433b-947b-f88a309814a2)

 - OS: ESP32
 - Browser: Flashing with esphome web in Chrome

**Additional context**
Tried with and without api: section commented out, it seems to be having some issue starting the api but otherwise I'm stumped

**Comment by kiguy2052** [comment]
OK, I was able to find some new information and potentially reproduce the issue. I started by downloading the most recent release on the github( aquapi-esp32.factory.bin) and flashing it. I join the AP, configure it to use my guest network, and let it connect. All looks good according to the logs: 
[logs (3).txt](https://github.com/user-attachments/files/16120430/logs.3.txt)

Then, I attempt to adopt it into ESPHome, which is where things go sideways. Immediately after esphome finishes uploading the api config, the bootloop begins occurring:
SC:
![image](https://github.com/TheRealFalseReality/aquapi/assets/10635940/5671537a-4a2e-4cfc-89f4-2d8eec01feda)
Logs:
[logs (4).txt](https://github.com/user-attachments/files/16120446/logs.4.txt)

Any ideas what might be causing this? Is anyone else able to reproduce?

**Comment by TheRealFalseReality** [comment]
Hmm, try doing it with `api:` defined, that allows it to connect to Home Assistant, it may reboot every 15 mins without connecting to an API. As for the ESPHome reboot, not sure. Try doing it without any pins connected to the ESP device, perhaps something is messing with the pins....  
Without anything connected, add these substitutions to the yaml so the logs aren't as cluttered with components that are not actually connected.
```
substitutions:
  update_ph: "never"
  update_ec: "never"
  update_do: "never"
  update_rtd: "never"
  update_pmp_1: "never" # Red
  update_pmp_2: "never" # Green
  update_pmp_3: "never" # White
  update_pmp_4: "never" # Orange
  update_pmp_5: "never" # Yellow
  update_pmp_6: "never" # Blue
  update_hum: "never"
  update_co2: "never"
  update_orp: "never"
  update_button_co2: "365days"
  update_button_ec: "365days"
  update_button_hum: "365days"
  ```

https://github.com/TheRealFalseReality/aquapi/wiki/Substitutions

**Comment by TheRealFalseReality** [comment]
You can also try adding packages, one at time. I have it all split up
In your yaml, try this:
```
packages:
  TheRealFalseReality.aquapi/common: 
    url: https://github.com/TheRealFalseReality/aquapi
    ref: main
    file: common/device_base_common.yaml
    refresh: 1s
  TheRealFalseReality.aquapi/esp32: 
    url: https://github.com/TheRealFalseReality/aquapi
    ref: main
    file: common/device_base.yaml
    refresh: 1s
```

This is just the packages that allow the ESP32 to boot properly, no other components activated.

**Comment by TheRealFalseReality** [comment]
> You can also try adding packages, one at time. I have it all split up In your yaml, try this:
> 
> ```
> packages:
>   TheRealFalseReality.aquapi/common: 
>     url: https://github.com/TheRealFalseReality/aquapi
>     ref: main
>     file: common/device_base_common.yaml
>     refresh: 1s
>   TheRealFalseReality.aquapi/esp32: 
>     url: https://github.com/TheRealFalseReality/aquapi
>     ref: main
>     file: common/device_base.yaml
>     refresh: 1s
> ```
> 
> This is just the packages that allow the ESP32 to boot properly, no other components activated.

replace the existing `packages` declaration.

**Comment by kiguy2052** [comment]
Alright, that stops it from bootlooping, and it is able to show basic info in HA. Adding more yamls in reveals the issue may be the ota_https package. Here's my yaml:
https://pastebin.com/S65ck3pi
and the logs:
[logs (6).txt](https://github.com/user-attachments/files/16120751/logs.6.txt)
I suspect having one pump on the multiconnector might be causing issues, so I'm goingn to try the inital default yaml setup without the multi-connector and return with results. Thank you for your quick reply!

**Comment by TheRealFalseReality** [comment]
Ok, lemme know. The `ota_https` is new, but works for me in testing. It's really only meant for AquaPi Firmware updates so I may need to remove it if it has issues.

**Comment by kiguy2052** [comment]
Yep, it appears to be the ota_https. Here's the yaml I'm running, with everything(I think) except ota_https, and it doesn't bootloop:
https://pastebin.com/fvh9uviN
and here's the logs
[logs_aquapi-a9eef8_logs.txt](https://github.com/user-attachments/files/16121078/logs_aquapi-a9eef8_logs.txt)
I remember seeing a bug report(on the esphome github i think) about devices bootlooping when loading wifi libraries before ota. something about ota lacking wireless as a requirement. couldn't find it when I went back through my history, but it could be somewhere to start

**Comment by TheRealFalseReality** [comment]
Ok, and I think I read somewhere having duplicate `ota:` in packages can cause issues. I simplified it, and made sure `ota:` is before `wifi:`. I updated it with some changes to `2024.6.4` if you wanna try that out.

**Comment by kiguy2052** [comment]
the aquapi does not boot after installing the updated image. For whatever reason, my camera also using your repository is booting just fine. i'm wondering if it could be the order of these in the yaml?
![image](https://github.com/TheRealFalseReality/aquapi/assets/10635940/7614a44c-abb5-4614-b8d6-047cf9197f0d)
camera yaml:
![image](https://github.com/TheRealFalseReality/aquapi/assets/10635940/94fe1365-c69f-4682-b701-ee3d2723bab1)
Maybe moving id: under icon: to match the camera config will make it work?

**Comment by kiguy2052** [comment]
shoot, just noticed the app_version: "2024.6.4". I'm using esphome 2024.6.6. might be important lol🤦‍♂️

**Comment by TheRealFalseReality** [comment]
no the `2024.6.4` is for the latest AquaPi

**Comment by TheRealFalseReality** [comment]
try building it without the ota_httpa entirely, I created a branch that removes that, and only that.

```
packages:
  TheRealFalseReality.aquapi: 
    url: https://github.com/TheRealFalseReality/aquapi
    ref: test-ota
    file: aquapi_config.yaml
    refresh: 1s
```
